clear; close all
% fix lag label text on correlation plots

fs_tx = 1e6;        % sample rate of transmitter
sps = 4;            % samples per symbol at transmitter
fs_rx = 200e6/22;   % sample rate of receiver
nzeros = 1000;     % number of zeros (in symbols) inserted by transmitter
npulse = 3000;      % pulse length (in symbols) generated by transmitter
nsamp_shift = 6700; % samples to shift in same ref frame as zeroes above
shift_up = 0.02;    % shift the zoomed in series for better viewing
peak_width = 20;    % number of samples to see on either side of corr peak
nstds = 70;          % draw threshold this many stds up

Ts_rx = 1/fs_rx;
fsym = fs_tx/sps;
Tsym = 1/fsym;
sps_rx = ceil(Tsym/Ts_rx);   % effective sps at receiver
nzeros = nzeros*sps_rx;     % number of samples for zeroes
npulse = npulse*sps_rx;     % number of samples for pulses
ns = nzeros+npulse;         % number of samples for both combined
nsamp_shift = sps_rx*nsamp_shift; % shift the correlating window

x1 = read_complex_binary('rx1.dat');
x2 = read_complex_binary('rx2.dat');
x3 = read_complex_binary('rx3.dat');

x1_slice = x1(bounds(1):bounds(2));
x2_slice = x2(bounds(1):bounds(2));
x3_slice = x3(bounds(1):bounds(2));
save('tx_center_record.mat','x1_slice','x2_slice','x3_slice','fs_rx',...
    'fs_tx','sps','npulse')


len_x1 = length(x1);
ncenter = floor(length(x1)/2);
bounds = nsamp_shift + [ncenter-floor(ns/2) ncenter+floor(ns/2)]; % focus on single pulse

figure
subplot(4,3,1)
plot(real(x1)); hold all
plot(imag(x1))
plot([bounds(1) bounds(1)], [-1 1], 'k--')
plot([bounds(2) bounds(2)], [-1 1], 'k--')
title('Rx1 192.168.10.2')
axis([-inf inf -0.01 0.01])
subplot(4,3,2)
plot(real(x2)); hold all
plot(imag(x2))
plot([bounds(1) bounds(1)], [-1 1], 'k--')
plot([bounds(2) bounds(2)], [-1 1], 'k--')
title('Rx2 192.168.10.4')
axis([-inf inf -0.01 0.01])
subplot(4,3,3)
plot(real(x3)); hold all
plot(imag(x3))
plot([bounds(1) bounds(1)], [-1 1], 'k--')
plot([bounds(2) bounds(2)], [-1 1], 'k--')
title('Rx3 192.168.10.5')
axis([-inf inf -0.01 0.01])

y1 = x1(bounds(1):bounds(2));
y2 = x2(bounds(1):bounds(2));
y3 = x3(bounds(1):bounds(2));
len_y1 = length(y1);

subplot(4,3,4:6)
plot(real(y1)+2*shift_up); hold all
plot(real(y2)+shift_up)
plot(real(y3))
title('Zoomed in Correlation Region')
xlabel('Sample Number')
ylabel('Magnitude')
legend('Rx1','Rx2','Rx3')
axis tight

[c12, lags12] = xcorr(y1,y2);
[c13, lags13] = xcorr(y1,y3);
cmag12 = abs(c12);
mean12 = mean(cmag12);
std12 = std(cmag12);
cmag13 = abs(c13);
mean13 = mean(cmag13);
std13 = std(cmag13);
[mval12, midx12] = max(cmag12);
[mval13, midx13] = max(cmag13);
clen = 2*len_y1-1;  % each xi stream should be equal length assumption
mlagidx12 = midx12-median(midx12);
mlagidx13 = midx13-median(midx13);

subplot(4,3,7:8)
plot(lags12, abs(c12)-mean12); hold all
plot([lags12(1) lags12(end)], [nstds*std12 nstds*std12], 'r--')
axis([lags12(1) lags12(end) -inf inf])
xlabel('Lag12')
ylabel('Correlation Magnitude')
title('Cross-correlation Rx1 and Rx2')
text(mlagidx12+10,mval12/2,sprintf('Lag Index of Peak: %i\nPeak Value: %f', mlagidx12, mval12))

subplot(4,3,9)
plot(lags12, abs(c12)-mean12, 'b.-', 'MarkerSize', 12); hold all
plot([-peak_width peak_width], [nstds*std12 nstds*std12], 'r--')
axis([mlagidx12-peak_width mlagidx12+peak_width -inf inf])
xlabel('Lag12')
ylabel('Correlation Magnitude')
title('Cross-correlation Rx1 and Rx2')

subplot(4,3,10:11)
plot(lags13, abs(c13)-mean13); hold all
plot([lags13(1) lags13(end)], [nstds*std13 nstds*std13], 'r--')
axis([lags13(1) lags13(end) -inf inf])
xlabel('Lag13')
ylabel('Correlation Magnitude')
title('Cross-correlation Rx1 and Rx3')
text(mlagidx13+10,mval13/2,sprintf('Lag Index of Peak: %i\nPeak Value: %f', mlagidx13, mval13))

subplot(4,3,12)
plot(lags13, abs(c13)-mean13, 'b.-', 'MarkerSize', 12); hold all
plot([-peak_width peak_width], [nstds*std13 nstds*std13], 'r--')
axis([mlagidx13-peak_width mlagidx13+peak_width -inf inf])
xlabel('Lag13')
ylabel('Correlation Magnitude')
title('Cross-correlation Rx1 and Rx3')